USE RestaurantApp

CREATE TABLE DishTypes(
	Id INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	Name NVARCHAR(100) NOT NULL UNIQUE)

CREATE TABLE MeasurementUnits(
	Id INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	Name NVARCHAR(100) NOT NULL UNIQUE)

GO

CREATE TABLE Products(
	Id INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	Name NVARCHAR(100) NOT NULL,
	MeasurementUnitId INT FOREIGN KEY REFERENCES MeasurementUnits(Id) NOT NULL,
	CONSTRAINT UX_MeasurementUnitId_Name UNIQUE(Name, MeasurementUnitId))

GO

CREATE TABLE Dishes(
	Id INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	DishTypeId INT FOREIGN KEY REFERENCES DishTypes(Id) NOT NULL,
	Name NVARCHAR(100) NOT NULL,
	CONSTRAINT UX_DishTypeId_Name UNIQUE(DishTypeId, Name))

GO

CREATE TABLE Ingredient(
	Id INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	DishId INT FOREIGN KEY REFERENCES Dishes(Id) NOT NULL,
	ProductId INT FOREIGN KEY REFERENCES Products(Id) NOT NULL,
	Amount REAL NOT NULL,
	CONSTRAINT CK_Amount_Not_Negative CHECK (Amount >= 0),
	CONSTRAINT UX_DishId_ProductId UNIQUE(DishId, ProductId))

GO

CREATE TABLE Orders(
	Id INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	OrderTime DateTime NOT NULL)

GO

CREATE TABLE DishesOrders(
	Id INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	DishId INT FOREIGN KEY REFERENCES Dishes(Id) NOT NULL,
	OrderId INT FOREIGN KEY REFERENCES Orders(Id) NOT NULL)
