USE RestaurantApp

CREATE TABLE DishTypes(
	Id INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	Name NVARCHAR(100) NOT NULL UNIQUE)

CREATE TABLE MeasurementUnits(
	Id INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	Name NVARCHAR(100) NOT NULL UNIQUE)

GO

CREATE TABLE Products(
	Id INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	Name NVARCHAR(100) NOT NULL,
	Cost MONEY NOT NULL,
	MeasurementUnitId INT FOREIGN KEY REFERENCES MeasurementUnits(Id) NOT NULL,
	CONSTRAINT UX_MeasurementUnitId_Name UNIQUE(Name, MeasurementUnitId),
	CONSTRAINT CK_Cost_Not_Negative CHECK(Cost >= 0))

GO

CREATE TABLE Dishes(
	Id INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	DishTypeId INT FOREIGN KEY REFERENCES DishTypes(Id) NOT NULL,
	ExtraCharge MONEY NOT NULL,
	Name NVARCHAR(100) NOT NULL,
	CONSTRAINT UX_DishTypeId_Name UNIQUE(DishTypeId, Name),
	CONSTRAINT CK_Extra_Charge_Not_Negative CHECK(ExtraCharge >= 0))

GO

CREATE TABLE Ingredients(
	Id INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	DishId INT FOREIGN KEY REFERENCES Dishes(Id) ON DELETE CASCADE NOT NULL,
	ProductId INT FOREIGN KEY REFERENCES Products(Id) NOT NULL,
	Amount REAL NOT NULL,
	CONSTRAINT CK_Ingredient_Amount_Not_Negative CHECK (Amount > 0),
	CONSTRAINT UX_DishId_ProductId UNIQUE(DishId, ProductId))

GO

CREATE TABLE Orders(
	Id INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	OrderTime DateTime NOT NULL)

GO

CREATE TABLE DishesOrders(
	Id INT PRIMARY KEY IDENTITY(1, 1) NOT NULL,
	DishId INT FOREIGN KEY REFERENCES Dishes(Id) NOT NULL,
	OrderId INT FOREIGN KEY REFERENCES Orders(Id) ON DELETE CASCADE NOT NULL,
	Amount REAL NOT NULL,
	CONSTRAINT CK_DishOrder_Amount_Not_Negative CHECK (Amount > 0),
	CONSTRAINT UX_DishId_OrderId UNIQUE(DishId, OrderId))